### ISSUE TITLE
Consider the library obsolete

### ISSUE THREAD

**Issue by chris-morgan** [reem/rust-typeable#3]
Since `AnyPrivate` was merged back into `Any`, the `get_type_id` method is available on `Any` again, removing the _raison d’être_ of this library.

Transition technique: `typeable::Typeable.get_type` -> `core::any::Any.get_type_id`.

**Comment by reem** [comment]
Since the trait is called AnyPrivate, I think it's likely it won't be around for long.

**Comment by chris-morgan** [comment]
It _was_ `AnyPrivate`, but when private trait bounds were forbidden (`pub trait Any: AnyPrivate` for `trait AnyPrivate`), that was no longer possible. There is no reason to expect this to disappear, especially as [the method is marked stable](http://doc.rust-lang.org/std/any/trait.Any.html#tymethod.get_type_id).

**Comment by reem** [comment]
I think it's entirely possible that in the future `AnyPrivate` might be collapsed into `Any`, with new associated statics features and better trait object and DST support.

**Comment by chris-morgan** [comment]
I don’t understand what you’re saying—there is no `AnyPrivate`, it’s a relic of history. `Any.get_type_id` exists and is `#[stable]`.

**Comment by reem** [comment]
It should probably not be stable then, since using virtual calls for this is very slow and should be unnecessary with associated statics. I will file an issue.

**Comment by reem** [comment]
All that said it's reasonable to expect this functionality will be available from Any, so this can be marked obsolete.

**Comment by reem** [comment]
`get_type_id` is no longer `#[stable]` for the above reasons, so this library is still useful for building on rust 1.0 in the near future once #7 is closed.
